/**
 * Componentes de interfaz de Rumbo (skill liquida-design). Importa siempre desde este barrel:
 *   import { Button, SectionCard } from '../components/ui'
 */
export { Button, ButtonLink, buttonClasses } from './Button'
export type { ButtonProps, ButtonLinkProps, ButtonStyleProps, ButtonVariant } from './Button'
export { IconButton } from './IconButton'
export type { IconButtonProps } from './IconButton'

export { Field } from './Field'
export type { FieldProps } from './Field'
export { SelectField } from './SelectField'
export type { SelectFieldProps, SelectOption } from './SelectField'
export { TextAreaField } from './TextAreaField'
export type { TextAreaFieldProps } from './TextAreaField'
export { SegmentedControl } from './SegmentedControl'
export type { SegmentedControlProps, SegmentedOption } from './SegmentedControl'
export { LanguageSwitch } from './LanguageSwitch'
export type { LanguageSwitchProps } from './LanguageSwitch'

export { Pill } from './Pill'
export type { PillProps, PillTone } from './Pill'
export { StatusPill } from './StatusPill'
export type { StatusPillProps, StatusPillStatus } from './StatusPill'
export { TripStatusPill, TRIP_STATE_META, TRIP_STATES, tripStateKey } from './TripStatusPill'
export type { TripStatusPillProps } from './TripStatusPill'
export { SatrackStatusPill } from './SatrackStatusPill'
export type { SatrackStatusPillProps } from './SatrackStatusPill'
export { FilterChip } from './FilterChip'
export type { FilterChipProps } from './FilterChip'
export { AlertCard } from './AlertCard'
export type { AlertCardProps } from './AlertCard'
export { EmptyState } from './EmptyState'
export type { EmptyStateProps } from './EmptyState'

export { SectionCard } from './SectionCard'
export type { SectionCardProps } from './SectionCard'
export { HeroPanel } from './HeroPanel'
export type { HeroPanelProps } from './HeroPanel'
export { Metric } from './Metric'
export type { MetricProps } from './Metric'
export { StatTile } from './StatTile'
export type { StatTileProps } from './StatTile'
export { ListRow } from './ListRow'
export type { ListRowProps } from './ListRow'

export { Spinner } from './Spinner'
export type { SpinnerProps } from './Spinner'
export { Skeleton } from './Skeleton'
export type { SkeletonProps } from './Skeleton'
export { Overline } from './Overline'
export type { OverlineProps } from './Overline'
export { PageHeader } from './PageHeader'
export type { PageHeaderProps } from './PageHeader'
export { Plate } from './Plate'
export type { PlateProps } from './Plate'
export { ConfirmDialog } from './ConfirmDialog'
export type { ConfirmDialogProps } from './ConfirmDialog'
