import subprocess
import sys
from pathlib import Path
from alembic import command
from tests.conftest import BACKEND, alembic_config


def test_modules_respect_their_boundaries():
    result = subprocess.run([str(Path(sys.executable).parent / "lint-imports")], cwd=BACKEND, capture_output=True, text=True)
    assert result.returncode == 0, result.stdout[-3000:]


def test_migrations_match_models(engine):
    # Reorganizar módulos no debe cambiar el esquema: lanza AutogenerateDiffsDetected si difieren.
    command.check(alembic_config())
