"""initial_schema"""
from alembic import op
import sqlalchemy as sa


revision = '5f22f636b715'
down_revision = None
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('transportadoras',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=200), nullable=False),
    sa.Column('nit', sa.String(length=30), nullable=False),
    sa.Column('frecuencia_consulta_min', sa.Integer(), nullable=False),
    sa.Column('creado_en', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('frecuencia_consulta_min BETWEEN 5 AND 10'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('conductores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('transportadora_id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=200), nullable=False),
    sa.Column('cedula', sa.String(length=10), nullable=False),
    sa.Column('telefono', sa.String(length=13), nullable=False),
    sa.Column('autoriza_contacto', sa.Boolean(), nullable=False),
    sa.Column('autorizado_en', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['transportadora_id'], ['transportadoras.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('transportadora_id', 'cedula')
    )
    op.create_index(op.f('ix_conductores_transportadora_id'), 'conductores', ['transportadora_id'], unique=False)
    op.create_table('cuentas_satelitales',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('transportadora_id', sa.Integer(), nullable=False),
    sa.Column('proveedor', sa.String(length=30), nullable=False),
    sa.Column('usuario', sa.String(length=200), nullable=False),
    sa.Column('password_cifrado', sa.Text(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('estado', sa.String(length=40), nullable=False),
    sa.Column('fallos_consecutivos', sa.Integer(), nullable=False),
    sa.Column('ultima_consulta_ok', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ultimo_error', sa.Text(), nullable=True),
    sa.Column('backoff_hasta', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['transportadora_id'], ['transportadoras.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('transportadora_id')
    )
    op.create_table('usuarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('transportadora_id', sa.Integer(), nullable=False),
    sa.Column('usuario', sa.String(length=100), nullable=False),
    sa.Column('nombre', sa.String(length=200), nullable=False),
    sa.Column('password_hash', sa.String(length=200), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('creado_en', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['transportadora_id'], ['transportadoras.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('usuario')
    )
    op.create_index(op.f('ix_usuarios_transportadora_id'), 'usuarios', ['transportadora_id'], unique=False)
    op.create_table('vehiculos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('transportadora_id', sa.Integer(), nullable=False),
    sa.Column('placa', sa.String(length=6), nullable=False),
    sa.Column('propietario', sa.String(length=200), nullable=False),
    sa.Column('en_satelital', sa.Boolean(), nullable=True),
    sa.Column('ultima_posicion_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['transportadora_id'], ['transportadoras.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('transportadora_id', 'placa')
    )
    op.create_index(op.f('ix_vehiculos_transportadora_id'), 'vehiculos', ['transportadora_id'], unique=False)
    op.create_table('consultas_satelitales',
    sa.Column('job_id', sa.String(length=36), nullable=False),
    sa.Column('transportadora_id', sa.Integer(), nullable=False),
    sa.Column('cuenta_satelital_id', sa.Integer(), nullable=False),
    sa.Column('cuenta_version', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.String(length=20), nullable=False),
    sa.Column('placas', sa.JSON(), nullable=False),
    sa.Column('enviado_en', sa.DateTime(timezone=True), nullable=False),
    sa.Column('respondido_en', sa.DateTime(timezone=True), nullable=True),
    sa.Column('estado', sa.String(length=20), nullable=False),
    sa.Column('error_codigo', sa.String(length=60), nullable=True),
    sa.Column('error_detalle', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['cuenta_satelital_id'], ['cuentas_satelitales.id'], ),
    sa.ForeignKeyConstraint(['transportadora_id'], ['transportadoras.id'], ),
    sa.PrimaryKeyConstraint('job_id')
    )
    op.create_index(op.f('ix_consultas_satelitales_transportadora_id'), 'consultas_satelitales', ['transportadora_id'], unique=False)
    op.create_index('uq_consulta_pendiente', 'consultas_satelitales', ['cuenta_satelital_id'], unique=True, postgresql_where=sa.text("estado = 'pendiente'"), sqlite_where=sa.text("estado = 'pendiente'"))
    op.create_table('sesiones',
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('creado_en', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expira_en', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('token_hash')
    )
    op.create_index(op.f('ix_sesiones_expira_en'), 'sesiones', ['expira_en'], unique=False)
    op.create_index(op.f('ix_sesiones_usuario_id'), 'sesiones', ['usuario_id'], unique=False)
    op.create_table('viajes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('transportadora_id', sa.Integer(), nullable=False),
    sa.Column('manifiesto', sa.String(length=40), nullable=False),
    sa.Column('conductor_id', sa.Integer(), nullable=False),
    sa.Column('vehiculo_id', sa.Integer(), nullable=False),
    sa.Column('origen', sa.String(length=200), nullable=False),
    sa.Column('destino', sa.String(length=200), nullable=False),
    sa.Column('salida_estimada', sa.DateTime(timezone=True), nullable=False),
    sa.Column('llegada_estimada', sa.DateTime(timezone=True), nullable=False),
    sa.Column('peso_salida_kg', sa.Float(), nullable=False),
    sa.Column('estado', sa.String(length=30), nullable=False),
    sa.Column('motivo_cancelacion', sa.Text(), nullable=True),
    sa.Column('creado_en', sa.DateTime(timezone=True), nullable=False),
    sa.Column('actualizado_en', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('llegada_estimada > salida_estimada'),
    sa.CheckConstraint('peso_salida_kg > 0'),
    sa.ForeignKeyConstraint(['conductor_id'], ['conductores.id'], ),
    sa.ForeignKeyConstraint(['transportadora_id'], ['transportadoras.id'], ),
    sa.ForeignKeyConstraint(['vehiculo_id'], ['vehiculos.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('transportadora_id', 'manifiesto')
    )
    op.create_index(op.f('ix_viajes_estado'), 'viajes', ['estado'], unique=False)
    op.create_index(op.f('ix_viajes_transportadora_id'), 'viajes', ['transportadora_id'], unique=False)
    op.create_index('uq_viaje_conductor_activo', 'viajes', ['conductor_id'], unique=True, postgresql_where=sa.text("estado IN ('registrado','programado','en_ruta','con_novedad')"), sqlite_where=sa.text("estado IN ('registrado','programado','en_ruta','con_novedad')"))
    op.create_index('uq_viaje_vehiculo_activo', 'viajes', ['vehiculo_id'], unique=True, postgresql_where=sa.text("estado IN ('registrado','programado','en_ruta','con_novedad')"), sqlite_where=sa.text("estado IN ('registrado','programado','en_ruta','con_novedad')"))
    op.create_table('eventos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('transportadora_id', sa.Integer(), nullable=False),
    sa.Column('viaje_id', sa.Integer(), nullable=True),
    sa.Column('usuario_id', sa.Integer(), nullable=True),
    sa.Column('tipo', sa.String(length=80), nullable=False),
    sa.Column('detalle', sa.JSON(), nullable=False),
    sa.Column('creado_en', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['transportadora_id'], ['transportadoras.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['viaje_id'], ['viajes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_eventos_transportadora_id'), 'eventos', ['transportadora_id'], unique=False)
    op.create_index(op.f('ix_eventos_viaje_id'), 'eventos', ['viaje_id'], unique=False)
    op.create_table('posiciones',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('transportadora_id', sa.Integer(), nullable=False),
    sa.Column('vehiculo_id', sa.Integer(), nullable=False),
    sa.Column('viaje_id', sa.Integer(), nullable=True),
    sa.Column('consulta_id', sa.String(length=36), nullable=False),
    sa.Column('lat', sa.Float(), nullable=True),
    sa.Column('lng', sa.Float(), nullable=True),
    sa.Column('velocidad_kmh', sa.Float(), nullable=True),
    sa.Column('direccion', sa.Text(), nullable=False),
    sa.Column('estado_gps', sa.String(length=80), nullable=False),
    sa.Column('reportado_en', sa.DateTime(timezone=True), nullable=True),
    sa.Column('reportado_texto', sa.String(length=250), nullable=False),
    sa.Column('capturado_en', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['consulta_id'], ['consultas_satelitales.job_id'], ),
    sa.ForeignKeyConstraint(['transportadora_id'], ['transportadoras.id'], ),
    sa.ForeignKeyConstraint(['vehiculo_id'], ['vehiculos.id'], ),
    sa.ForeignKeyConstraint(['viaje_id'], ['viajes.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('vehiculo_id', 'reportado_en')
    )
    op.create_index(op.f('ix_posiciones_transportadora_id'), 'posiciones', ['transportadora_id'], unique=False)
    op.create_index('ix_posiciones_viaje_fecha', 'posiciones', ['viaje_id', 'capturado_en'], unique=False)
    op.create_table('remesas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('transportadora_id', sa.Integer(), nullable=False),
    sa.Column('viaje_id', sa.Integer(), nullable=False),
    sa.Column('numero', sa.String(length=80), nullable=False),
    sa.Column('cliente', sa.String(length=200), nullable=False),
    sa.Column('peso_kg', sa.Float(), nullable=False),
    sa.Column('cantidad', sa.Integer(), nullable=True),
    sa.CheckConstraint('peso_kg > 0'),
    sa.ForeignKeyConstraint(['transportadora_id'], ['transportadoras.id'], ),
    sa.ForeignKeyConstraint(['viaje_id'], ['viajes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('viaje_id', 'numero')
    )
    op.create_index(op.f('ix_remesas_transportadora_id'), 'remesas', ['transportadora_id'], unique=False)
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_remesas_transportadora_id'), table_name='remesas')
    op.drop_table('remesas')
    op.drop_index('ix_posiciones_viaje_fecha', table_name='posiciones')
    op.drop_index(op.f('ix_posiciones_transportadora_id'), table_name='posiciones')
    op.drop_table('posiciones')
    op.drop_index(op.f('ix_eventos_viaje_id'), table_name='eventos')
    op.drop_index(op.f('ix_eventos_transportadora_id'), table_name='eventos')
    op.drop_table('eventos')
    op.drop_index('uq_viaje_vehiculo_activo', table_name='viajes', postgresql_where=sa.text("estado IN ('registrado','programado','en_ruta','con_novedad')"), sqlite_where=sa.text("estado IN ('registrado','programado','en_ruta','con_novedad')"))
    op.drop_index('uq_viaje_conductor_activo', table_name='viajes', postgresql_where=sa.text("estado IN ('registrado','programado','en_ruta','con_novedad')"), sqlite_where=sa.text("estado IN ('registrado','programado','en_ruta','con_novedad')"))
    op.drop_index(op.f('ix_viajes_transportadora_id'), table_name='viajes')
    op.drop_index(op.f('ix_viajes_estado'), table_name='viajes')
    op.drop_table('viajes')
    op.drop_index(op.f('ix_sesiones_usuario_id'), table_name='sesiones')
    op.drop_index(op.f('ix_sesiones_expira_en'), table_name='sesiones')
    op.drop_table('sesiones')
    op.drop_index('uq_consulta_pendiente', table_name='consultas_satelitales', postgresql_where=sa.text("estado = 'pendiente'"), sqlite_where=sa.text("estado = 'pendiente'"))
    op.drop_index(op.f('ix_consultas_satelitales_transportadora_id'), table_name='consultas_satelitales')
    op.drop_table('consultas_satelitales')
    op.drop_index(op.f('ix_vehiculos_transportadora_id'), table_name='vehiculos')
    op.drop_table('vehiculos')
    op.drop_index(op.f('ix_usuarios_transportadora_id'), table_name='usuarios')
    op.drop_table('usuarios')
    op.drop_table('cuentas_satelitales')
    op.drop_index(op.f('ix_conductores_transportadora_id'), table_name='conductores')
    op.drop_table('conductores')
    op.drop_table('transportadoras')
    # ### end Alembic commands ###
