export const copy = {
  "es": {
    "nav_agents": "Agentes",
    "nav_how": "Cómo funciona",
    "nav_approach": "Nuestro enfoque",
    "nav_contact": "Contacto",
    "nav_cta": "Hablemos del piloto",
    "hero_eyebrow": "Agentes para el mercado de la logística",
    "hero_title_a": "Tu operación avanza.",
    "hero_title_b": "Tus agentes la acompañan.",
    "hero_description": "Diseñamos agentes de IA para acompañar tus viajes de carga, dar seguimiento al conductor y reunir los documentos de cada entrega. Más contexto para tu operación, con tu equipo siempre al mando.",
    "hero_cta": "Hablemos de tu operación",
    "hero_secondary": "Conoce cómo funciona",
    "hero_note": "Buscamos transportadoras para nuestros primeros pilotos.",
    "diagram_label": "De la salida al cierre",
    "diagram_title": "Un viaje. Un equipo de agentes.",
    "diagram_caption": "Así está pensado el trabajo de los agentes en tu operación.",
    "diagram_step1": "Acompañar la ruta",
    "diagram_step1_note": "Ubicación y novedades alrededor del viaje.",
    "diagram_step2": "Mantener la conversación",
    "diagram_step2_note": "Contacto y seguimiento con el conductor.",
    "diagram_step3": "Preparar el cumplido",
    "diagram_step3_note": "Documentos organizados para revisión humana.",
    "diagram_footer": "Los agentes acompañan. Tu equipo decide.",
    "tools_eyebrow": "Pensado para las herramientas que ya conoces",
    "tool1": "Tu satelital",
    "tool2": "WhatsApp",
    "tool3": "Llamadas",
    "tool4": "Tus documentos",
    "benefits_eyebrow": "Contexto en cada paso.",
    "benefits_title": "Agentes que entienden la operación.",
    "benefits_description": "Seguimiento, conversaciones y cumplidos. El trabajo que conecta cada viaje.",
    "benefit1_title": "Seguimiento con contexto",
    "benefit1_body": "Reunir señales del satelital y novedades para que tu equipo sepa dónde poner su atención durante el viaje.",
    "benefit2_title": "La conversación al día",
    "benefit2_body": "Acompañar la comunicación con el conductor por WhatsApp o llamada y organizar lo que pasa durante la ruta.",
    "benefit3_title": "Cada entrega, lista para revisar",
    "benefit3_body": "Ayudar a recuperar los cumplidos y preparar la información para que una persona revise y apruebe el cierre.",
    "how_eyebrow": "Así empieza el camino",
    "how_title": "Encaja en tu manera de trabajar.",
    "how_description": "Empezamos con un flujo concreto de tu operación y lo construimos contigo.",
    "how1_title": "Conocemos tu operación",
    "how1_body": "Revisamos cómo acompañas tus viajes, qué herramientas usas y dónde se acumula el trabajo manual.",
    "how2_title": "Definimos el trabajo de los agentes",
    "how2_body": "Acordamos qué seguir, a quién contactar y cuándo debe intervenir tu equipo.",
    "how3_title": "Probamos y medimos contigo",
    "how3_body": "Empezamos con un piloto acompañado y medimos lo que cambia en el seguimiento y cierre de tus viajes.",
    "control_eyebrow": "Personas al mando",
    "control_title": "Más apoyo para tu equipo. Las decisiones siguen siendo tuyas.",
    "control_body": "Rumbo está diseñado para que los agentes reúnan contexto y preparen el trabajo. Tu equipo revisa las excepciones y aprueba los pasos que lo requieren.",
    "control_point1": "Revisión humana antes de aprobar un cumplido.",
    "control_point2": "Información y contexto para atender cada novedad.",
    "control_point3": "Un piloto acompañado para validar lo que funciona.",
    "audience_eyebrow": "Para quienes mueven la logística",
    "audience_title": "Construido alrededor de tu trabajo.",
    "audience_body": "Empezamos con un flujo concreto de seguimiento y cierre de viajes de carga.",
    "audience1_title": "Transportadoras",
    "audience1_body": "Que buscan acompañar sus viajes y organizar el cierre de cada entrega.",
    "audience2_title": "Equipos de tráfico",
    "audience2_body": "Que necesitan contexto para atender novedades y priorizar pendientes.",
    "audience3_title": "Operadores logísticos",
    "audience3_body": "Que buscan agentes adaptados a sus procesos y herramientas.",
    "pilot_eyebrow": "Un primer paso, bien acompañado",
    "pilot_title": "El próximo viaje lo construimos contigo.",
    "pilot_body": "Buscamos transportadoras para definir un primer piloto. Acordamos un alcance concreto según tu operación y las herramientas que ya usas.",
    "pilot_item1": "Un flujo de tu operación para empezar.",
    "pilot_item2": "Acompañamiento durante la prueba.",
    "pilot_item3": "Resultados medidos antes de ampliar.",
    "pilot_cta": "Hablemos del piloto",
    "faq_eyebrow": "Antes de empezar",
    "faq_title": "Lo que quizá te estés preguntando.",
    "faq1_q": "¿Qué son los agentes de Rumbo?",
    "faq1_a": "Son agentes de IA diseñados para acompañar tareas de la operación logística: seguimiento, conversaciones y documentos. Su alcance se define con tu equipo durante el piloto.",
    "faq2_q": "¿Mis conductores necesitan otra app?",
    "faq2_a": "La propuesta inicial usa los canales que ya conocen, como WhatsApp y llamadas, sin exigir una app al conductor. Las integraciones se confirman para cada piloto.",
    "faq3_q": "¿Los agentes toman las decisiones por mí?",
    "faq3_a": "Tu equipo conserva el control. Los agentes reúnen información y preparan el trabajo; una persona revisa las excepciones y las aprobaciones que lo requieren.",
    "faq4_q": "¿Cuánto cuesta empezar?",
    "faq4_a": "El precio todavía no está definido. Conversemos sobre las necesidades de tu operación y el alcance del piloto antes de empezar.",
    "contact_eyebrow": "Hablemos de logística",
    "contact_title": "Dale un nuevo rumbo a tu operación.",
    "contact_body": "Cuéntanos cómo trabajas y qué pendientes te gustaría resolver. El primer paso es una conversación.",
    "contact_pending": "Canal de contacto por confirmar",
    "contact_cta": "Conversemos",
    "footer_tagline": "Tu operación, al día.",
    "footer_location": "Hecho para la logística en Colombia.",
    "footer_note": "Agentes para acompañar la logística.",
    "problem_eyebrow": "El trabajo entre las herramientas",
    "problem_title": "La información está repartida. Tu equipo tiene que reunirla.",
    "problem_body": "Una ubicación en el satelital, una novedad por WhatsApp y el cumplido en una foto. Para cerrar el viaje, el equipo de tráfico conecta cada pieza.",
    "problem1_title": "Consultar la ubicación",
    "problem1_body": "Volver al satelital para entender cómo avanza cada camión.",
    "problem2_title": "Pedir novedades y documentos",
    "problem2_body": "Llamar o escribir al conductor y revisar lo que todavía falta.",
    "problem3_title": "Reunir todo para el cierre",
    "problem3_body": "Relacionar documentos, remesas y novedades antes de aprobar el cumplido.",
    "faq5_q": "¿Tengo que cambiar mis herramientas?",
    "faq5_a": "Partimos de tu forma de trabajar. Durante el piloto revisamos tu satelital, WhatsApp y los archivos que usas hoy, y acordamos qué se puede conectar para empezar con un flujo concreto.",
    "faq6_q": "¿Con qué satelital está pensado el primer piloto?",
    "faq6_a": "El alcance inicial está planteado alrededor de Satrack. Confirmamos el acceso y las condiciones con cada transportadora; otros proveedores se evalúan según la operación."
  },
  "en": {
    "nav_agents": "Agents",
    "nav_how": "How it works",
    "nav_approach": "Our approach",
    "nav_contact": "Contact",
    "nav_cta": "Talk about a pilot",
    "hero_eyebrow": "Agents for the logistics industry",
    "hero_title_a": "Your operation keeps moving.",
    "hero_title_b": "Your agents keep pace.",
    "hero_description": "We design AI agents to support your freight trips, follow up with drivers and gather delivery documents. More context for your operation, with your team always in control.",
    "hero_cta": "Talk about your operation",
    "hero_secondary": "See how it works",
    "hero_note": "We’re looking for carriers for our first pilots.",
    "diagram_label": "From departure to closeout",
    "diagram_title": "One trip. A team of agents.",
    "diagram_caption": "How our agents are designed to support your operation.",
    "diagram_step1": "Follow the route",
    "diagram_step1_note": "Location signals and updates around each trip.",
    "diagram_step2": "Keep the conversation going",
    "diagram_step2_note": "Communication and follow-up with drivers.",
    "diagram_step3": "Prepare proof of delivery",
    "diagram_step3_note": "Documents organized for human review.",
    "diagram_footer": "Agents support the work. Your team decides.",
    "tools_eyebrow": "Designed around the tools you already know",
    "tool1": "Your telematics",
    "tool2": "WhatsApp",
    "tool3": "Phone calls",
    "tool4": "Your documents",
    "benefits_eyebrow": "Context at every step.",
    "benefits_title": "Agents that understand the operation.",
    "benefits_description": "Trip monitoring, conversations and proof of delivery. The work that connects every trip.",
    "benefit1_title": "Context for trip monitoring",
    "benefit1_body": "Bring together telematics signals and trip updates so your team knows where to focus along the way.",
    "benefit2_title": "Keep conversations on track",
    "benefit2_body": "Support communication with drivers by WhatsApp or phone and organize what happens along the route.",
    "benefit3_title": "Every delivery, ready for review",
    "benefit3_body": "Help collect proof of delivery and prepare the information for a person to review and approve closeout.",
    "how_eyebrow": "Where the journey begins",
    "how_title": "Fits the way you work.",
    "how_description": "We start with a focused workflow in your operation and build it with you.",
    "how1_title": "Understand your operation",
    "how1_body": "We review how you follow your trips, the tools you use and where manual work builds up.",
    "how2_title": "Define the agents’ work",
    "how2_body": "We agree on what to monitor, whom to contact and when your team needs to step in.",
    "how3_title": "Test and measure together",
    "how3_body": "We start with a supported pilot and measure what changes in trip monitoring and closeout.",
    "control_eyebrow": "People stay in control",
    "control_title": "More support for your team. Decisions remain yours.",
    "control_body": "Rumbo is designed for agents to gather context and prepare the work. Your team reviews exceptions and approves the steps that need a human decision.",
    "control_point1": "Human review before proof of delivery is approved.",
    "control_point2": "Information and context for every trip update.",
    "control_point3": "A supported pilot to validate what works.",
    "audience_eyebrow": "For the people who keep logistics moving",
    "audience_title": "Built around your work.",
    "audience_body": "We’re starting with a focused workflow for freight trip monitoring and closeout.",
    "audience1_title": "Carriers",
    "audience1_body": "Looking to support their trips and organize the closeout of every delivery.",
    "audience2_title": "Dispatch teams",
    "audience2_body": "Needing context to handle trip updates and prioritize open items.",
    "audience3_title": "Logistics operators",
    "audience3_body": "Looking for agents adapted to their processes and tools.",
    "pilot_eyebrow": "A first step, with support",
    "pilot_title": "Let’s build the next journey together.",
    "pilot_body": "We’re looking for carriers to define a first pilot. We agree on a focused scope based on your operation and the tools you already use.",
    "pilot_item1": "One operational workflow to start.",
    "pilot_item2": "Support throughout the pilot.",
    "pilot_item3": "Measured results before scaling up.",
    "pilot_cta": "Talk about the pilot",
    "faq_eyebrow": "Before we get started",
    "faq_title": "A few things you might be wondering.",
    "faq1_q": "What are Rumbo’s agents?",
    "faq1_a": "They are AI agents designed to support logistics tasks: monitoring trips, communicating and gathering documents. We define their scope with your team during the pilot.",
    "faq2_q": "Do my drivers need another app?",
    "faq2_a": "The initial proposal uses familiar channels such as WhatsApp and phone calls, without requiring a driver app. Integrations are confirmed for each pilot.",
    "faq3_q": "Do the agents make decisions for me?",
    "faq3_a": "Your team stays in control. Agents gather information and prepare the work; a person reviews exceptions and the approvals that require human judgment.",
    "faq4_q": "How much does it cost to start?",
    "faq4_a": "Pricing has not been set yet. Let’s discuss your operation’s needs and the pilot scope before getting started.",
    "contact_eyebrow": "Let’s talk logistics",
    "contact_title": "Give your operation a new direction.",
    "contact_body": "Tell us how you work and which open items you want to resolve. The first step is a conversation.",
    "contact_pending": "Contact channel to be confirmed",
    "contact_cta": "Let’s talk",
    "footer_tagline": "Your operation, on track.",
    "footer_location": "Built for logistics in Colombia.",
    "footer_note": "Agents to support logistics.",
    "problem_eyebrow": "The work between your tools",
    "problem_title": "Information lives in different places. Your team brings it together.",
    "problem_body": "A location in your tracking system, an update on WhatsApp and proof of delivery in a photo. To close out the trip, your dispatch team connects every piece.",
    "problem1_title": "Check the location",
    "problem1_body": "Return to the tracking system to understand how each truck is progressing.",
    "problem2_title": "Request updates and documents",
    "problem2_body": "Call or message the driver and review what is still missing.",
    "problem3_title": "Bring everything together for closeout",
    "problem3_body": "Match documents, consignment notes and updates before approving proof of delivery.",
    "faq5_q": "Do I need to change my tools?",
    "faq5_a": "We start with the way you work. During the pilot, we review your tracking system, WhatsApp and the files you use today, then agree on what can be connected to start with one focused workflow.",
    "faq6_q": "Which tracking system is the first pilot designed around?",
    "faq6_a": "The initial scope is designed around Satrack. We confirm access and requirements with each carrier; other providers are evaluated according to the operation."
  }
};
