from typing import Protocol
from app.schemas import Account, Position, Vehicle


class Provider(Protocol):
    name: str
    def fetch_positions(self, account: Account) -> list[Position]: ...
    def list_vehicles(self, account: Account) -> list[Vehicle]: ...
    def cancel(self, account_id: str) -> None: ...
    def close(self) -> None: ...
